CREATE DATABASE doingsdone
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(60) NOT NULL,
email VARCHAR(128) NOT NULL UNIQUE,
password VARCHAR(64) NOT NULL UNIQUE,
date_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE projects (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED NOT NULL,
headline_project VARCHAR(255) NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE tasks (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
status TINYINT(1) DEFAULT 0 NOT NULL,
title VARCHAR(255) NOT NULL,
file_path VARCHAR(255) NULL,
deadline_date TIMESTAMP NULL,
user_id INT UNSIGNED NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
project_id INT UNSIGNED NOT NULL,
FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX status ON tasks (status);
CREATE INDEX create_date ON tasks (create_date);
