CREATE DATABASE Doingsdone
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE Doingsdone;

CREATE TABLE Users (
Id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
Date_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
Email VARCHAR(128) NOT NULL,
Name VARCHAR(60) NOT NULL,
Password VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE Projects (
Id INT AUTO_INCREMENT PRIMARY KEY,
Headline_project VARCHAR(255) NOT NULL,
User_id INT NOT NULL,
FOREIGN KEY (User_id) REFERENCES Users(Id)
);

CREATE TABLE Tasks (
Id INT AUTO_INCREMENT PRIMARY KEY,
Create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
Status TINYINT(1) DEFAULT 0 NOT NULL,
Title VARCHAR(255) NOT NULL,
File_path VARCHAR(255) NULL,
Deadline_date TIMESTAMP NULL,
User_id INT NOT NULL,
FOREIGN KEY (User_id) REFERENCES Users(Id),
Project_id INT NOT NULL,
FOREIGN KEY (Project_id) REFERENCES Projects(Id)
);
